### ISSUE TITLE
Diving in.  

### ISSUE THREAD

**Issue by Svengali** [jbakic/Shielded.Gossip#4]
(Couldnt see a spot to say hello or anything)

I was writing my own distributed STM system, then I realized yours does nearly everyting I would like it to do.  So why not dive in.  

Im using this for massively distributed game servers.  State changes a lot.  Different state changes on different servers (for example, on the physics server position, rotation changes, but on the Rules server, health can change).  

Game objects are called Entitys.  An Entity is a bag of components.  Components do the heavy lifting for state and functionality.  In my system theyre also Versioned because certain big thing dont change a lot (like say your inventory).

Ive used a non-distributed in-house implementation of STM on another project and watched it scale to 3000 players playing their hearts out in the same battle on a 36 core AWS instance.  Rollbacks were rare, roughly 1 / second unless there was a bug.  Tick rate was 33ms for physics, and could flow down to 100ms if too much was going down.  It was a bit unoptimized. 

Im using Ceras for serialization, its pretty awesome.  

Speed is relatively important.  'Fast' changes for this frame should all happen roughly within 33ms.  Id be ok with a 50ms update rate if 33 couldnt be hit.  

Certain changes to Entitys need to be distributed atomic, while others do not have to be. 

I only mention all this because my goals might have me have different requirements than you do.

**Comment by jbakic** [comment]
Hi! Thanks for reaching out. I'd be glad to help as I can.

I believe everything you need is doable. My main goals are to offer something simple, practical and fast, and in a way that is easy to combine with other means and extend it in any way desired.

You will have to test the performance for yourself, of course. I think 10k trans/sec is achievable in the eventually consistent mode, and at least 200 trans/sec for the fully consistent mode, but it's hard to say, since I run basic perf tests on my own machine. And it should be faster if you change the serializer - I stick to standard .NET stuff to avoid pushing dependencies on library users. But bear in mind, the consistent transactions depend on network latency - agreement requires at least two hops - so they are probably not as fast as you might need. Batched, they reach some throughput, but their individual latency will probably break your latency budget.

This is still a work in progress, so FYI, some of the things I'm planning to add soon:
* Message limiting by size - currently you can only limit by key count, but in case the fields are of wildly varying size, a limit on the size would be useful.
* Exponential back-off for the TcpTransport - it curently drops pending messages if it fails to connect, which represents a mild back-off, but it tries connecting again as soon as a new message is enqueued. However, you can use any existing messaging library, so this is maybe not relevant.
* Auto-commit option for consistent transactions - a way to indicate to the network that the initiator is not interested in delaying the commit, which allows the network to commit/fail a consistent transaction even if he becomes unavailable.

There's a lot more stuff that I want to do, some lower level features, and some higher level, like implementing certain more common patterns in the library itself. I hope it can already be useful to you, and I'd love to get your feedback about how it works out!

**Comment by jbakic** [comment]
A small correction - the consistent mode is actually finished after one hop. As soon as the initiator receives positive preparation results from a majority of servers, he'll declare success and the RunConsistent task will be resolved. Other servers get notified about the commit in the background, as there's currently no waiting for commit confirmation from them. That does mean that a later non-consistent read on another server could return the old value, but to stop that we'd have to wait for all of them to confirm, which means blockages as soon as one is unavailable. What really matters, I think, is that a RunConsistent read will definitely see the correct value.

Also, the message limiting by size feature is now in.

I'd be happy to hear what you think. I'm curious if this makes sense for your use case, or if not, if there's maybe something I could focus on improving.

**Comment by Svengali** [comment]
Ive gotten a handle on the features, and Im now integrating it into my own service architecture.  

I added some state tracking in the TcpTransport class for servers, as well as the ability to connect to servers later.  Its not in a pull request state yet because its just prototypy.  

On further reflection, Ill probably make a custom TcpTransport that does those things and keep yours how it is, unless you think thats a generally useable set of ideas.  

Im also using the Ceras serialization library, so Ill let you know how well that works.  

For testing, Im going to be running $15 DigitalOcean servers.  Theyre 2.2 cents a server, so Ill be bringing up a few, then shutting them down.  I might use Google Cloud, unsure.

**Comment by jbakic** [comment]
Re. the TcpTransport, maybe you can push the changes into a new branch on your fork of the project, so that I can have a look? I don't know what you mean exactly.

As for Ceras and the testing, I'd love to hear how it works out, thanks!

**Comment by Svengali** [comment]
Hilarious.  You just made TcpTransport always connect, which is effectively all I did.  Mine had an extra enum for what was going on, like Connecting, Connected, Dropped, etc.  They arent strictly necessary, but its good for things like logging.  

Im going to back my changes out and just use yours.  

Ill probably add something like ILog or somesuch, and add logging.  I dont know what the common best practice is for a library to log.  I have a custom logger because I find most the bigger libraries are just much more than I need.  And, I lean heavily on structured logging.  

I dropped a .editorconfig at the front of your 2 projects.  I didnt check them in or anything.  I use a .editorconfig a couple of directories up for ALL my libraries and projects, but wanted to keep your projects the same as what you use.  I use 2 char tabs instead of the much more common 4 char spaces.

**Comment by jbakic** [comment]
So, you noticed the same issue :) It was a really bad idea to use a new connection for every single message...

As for logging, it would definitely be a good improvement to the lib. I guess there's two options: 1) add an ILog interface, with default impl that does nothing, or 2) add a kind of monitoring event which fires whenever something potentially interesting for monitoring happens, where the handler receives an abstract class arg which, depending on the event, would be an instance of a subclass with event-specific info. I'm guessing option 2 might be more appealing for structured logging, while still being relatively general. A ToString impl is all it takes to support easy transforming of the event classes into a string for logging... What do you think?

**Comment by jbakic** [comment]
I'm reading online right now, and the best advice seems to be to avoid logging, or to use either Microsoft.Extensions.Logging.Abstractions (ask for ILogger in the constructor), or [LibLog](https://github.com/damianh/LibLog), which automagically finds out what logging lib the library user is using... I'm definitely leaning towards the events option :) And I'd really like to keep it as simple as possible. What would you like to log? All messages? Connection state changes?

**Comment by jbakic** [comment]
Closing issue, it's obsolete.
