### ISSUE TITLE
Add hooks for loggin

### ISSUE THREAD

**Issue by Svengali** [jbakic/Shielded.Gossip#5]
(thought I would make a new issue)

Distributed systems live and die on good logging.  But also every organization has their own logging setups.  From purely local file logging, to elasticsearch, to zipkin.  

I propose adding hooks into the system.  

jbakic mentioned either an ILog style system with functions like

void trace( string message, object obj, <file/line> ); 
void debug( string message, object obj, <file/line> ); 
void info( string message, object obj, <file/line> ); 
void warn( string message, object obj, <file/line> ); 
void high( string message, object obj, <file/line> ); 
void error( string message, object obj, <file/line> ); 
void exception( string message, Exception ex, object obj, <file/line> ); 
void fatal( string message, object obj, <file/line> ); 

Where the obj is a context object for structured logging.

Or an event system.  

I like both of them.  I think I lean towards the ILog style system.

**Comment by jbakic** [comment]
Hi there! I finally got around to implementing the logging. Please take a look and let me know what you think: 2ea5d656290d00ca8b05a55d68123d7f586d133e

I chose to use Microsoft.Extensions.Logging.Abstractions. It has NuGet packages for all major .NET logging libraries, so it should be easy to use without requiring the library user to implement anything. And also, it has support for structured logging, which I think you'll appreciate.

Most of the logging I added is in the DEBUG level, since the lib can produce a lot of loglines, and it's usually not interesting. Exceptions to this are status changes of TCP connections, and of course, any errors. Also, if gossip synchronization ever fails to reach successful conclusion, that will be a warning.

**Comment by Svengali** [comment]
Super awesome!  Thank you very much.  Ive taken some time off, but Im digging back in.

**Comment by jbakic** [comment]
Logging is done, so closing issue. If changes will be needed, please open a new issue.
